### ISSUE TITLE
This ain't simple at all

### ISSUE THREAD

**Issue by marktopper** [codezero-be/twitter#1]
In simple I think of a few lines of coding.

But in order to get a actual tweet I currently uses the following lines in order to just search twitter for tweets:

```
    $curl = new \CodeZero\Curl\Curl();
    $optionParser = new \CodeZero\Curl\OptionParser();
    $responseFactory = new \CodeZero\Curl\ResponseFactory();
    $curlRequest = new \CodeZero\Curl\Request($curl, $optionParser, $responseFactory);
    $responseCodes = new \CodeZero\Courier\ResponseCodes();
    $responseParser = new \CodeZero\Courier\CurlResponseParser($responseCodes);
    $cache = null;
    $courier = new \CodeZero\Courier\CurlCourier($curlRequest, $responseParser, $cache);
    $config = app_path() . '/config/packages/codezero/twitter/config.php';
    $loader = new \CodeZero\Configurator\Loader();
    $configurator = new \CodeZero\Configurator\Configurator($loader, $config);
    $twitterCourier = new \CodeZero\Twitter\TwitterCourier($courier);
    $authHelper = new \CodeZero\Twitter\AuthHelper();
    $urlHelper = new \CodeZero\Utilities\UrlHelper();
    $twitterFactory = new \CodeZero\Twitter\TwitterFactory();
    $twitter = new \CodeZero\Twitter\Twitter($configurator, $twitterCourier, $authHelper, $urlHelper, $twitterFactory);
    $query = '#laravel';
    $count = 1;
    $cacheMinutes = 30;
    $returnEntities = true;
    $tweets = $twitter->searchTweets($query, $count, $cacheMinutes, $returnEntities);
```

I just think it is a little overkill, why not loading some of those inside the actually Twitter class?

**Comment by ivanvermeyen** [comment]
Hi,
I agree. I am planning to find some way to simplify this process, as it is indeed a bit cumbersome... My primary goal was to use this in a Laravel application, where all of the dependencies are resolved automatically by the IoC container. When I have the time I will certainly be revisiting all of the packages to simplify them and making them work together more seemlessly without Laravel.
Thanks for the feedback! :)

**Comment by marktopper** [comment]
Thanks.
I will be watching this repo to keep myself updated.

Let me know if you need any help?

mail: mail@webman.io

**Comment by ivanvermeyen** [comment]
Hi, I've made most of the dependencies optional now. If you don't specify them, defaults will be instantiated. I should probably use interfaces instead of injecting concretes so they are swappable, but that's for a future update :) I'm still learning as I go :) You should now be able to do something like this:

```
use CodeZero\Twitter\Twitter;
$config = '/path/to/configFile.php';
$twitter = new Twitter($config);
```

**Comment by marktopper** [comment]
:+1: Brilliant!

**Comment by ivanvermeyen** [comment]
More improvements coming soon :) Looking to implement https://github.com/khoaofgod/phpfastcache for caching with non-Laravel projects. Also working on a similar Facebook (Page) and Flickr package.
